### ISSUE TITLE
Add support for both prototxt and protobin filetype

### ISSUE THREAD

**Issue by yanghuanflc** [solrex/caffe-mobile#14]
Would it be possible for you to add support for both prototxt and protobin filetype?

**Comment by yanghuanflc** [comment]
I'm doing this by adding "add_definitions(-DUSE_PROTOBUF_FULL)" in CMakeLists.txt and change "option optimize_for = SPEED;" in caffe.proto.
Am I right?

**Comment by solrex** [comment]
Yes, you're right. But the final lib size is much larger than the building for `.protobin` format.

**Comment by yanghuanflc** [comment]
I think you are right, I choose to use protobin at last.
