### ISSUE TITLE
size and speed for caffe mobile

### ISSUE THREAD

**Issue by pby5** [solrex/caffe-mobile#15]
你好，能简单介绍下caffe mobile在size和speed方面是如何改进的

**Comment by yanghuanflc** [comment]
你好，我记得你发布了MobileNet在Caffe上的prototxt，但是经过测试好像并没有很大的优化，可以解释一下原因吗？ @pby5

**Comment by solrex** [comment]
@pby5 speed上主要是用ios上的accelerate framework、android上用ARM intrinsic加速了一些在blas库之外的数学计算，性能上有一些改进，但我没有 benchmark 过，所以也不好说多少；size 上是去掉了很多库的依赖但不影响功能，从编出来的 lib 大小上你可以直观感受到。

**Comment by yanghuanflc** [comment]
@solrex 我之前也有维护一个caffe mobile的版本，也是用的accelerate framework，但是感觉没有你的这么elegant，赞一个～

**Comment by pby5** [comment]
@yanghuanflc mobileney 在caffe不快的原因的是因为利用caffe中group来计算depthwise conv，如果想要快的需要自己实现下kernel

**Comment by pby5** [comment]
我认为speed这块主要在底层的矩阵库运算，不过目前免费且最好的应该是openblas
