### ISSUE TITLE
windows上能移植吗

### ISSUE THREAD

**Issue by piaobuliao** [solrex/caffe-mobile#16]
windows上能移植吗,官方的caffe在windows上依赖一堆的库,用你这个好像就依赖很少哦,能移植到windows上吗

**Comment by solrex** [comment]
@piaobuliao 这个库主要是用来预测，不是用来训练。所以如果你是将已有的模型集成到Windows应用程序中，用来预测是可以的；但如果想在Windows跑Caffe训练，这个库做不到。

**Comment by piaobuliao** [comment]
我就只是想做预测,那集成到Windows应用程序直接用cmake调用你的源代码就能生成?

**Comment by zchrissirhcz** [comment]
Hi, 我尝试着在windows上修改了编译脚本，编译和android手机上运行都OK，提交了PR https://github.com/solrex/caffe-mobile/pull/17

**Comment by solrex** [comment]
@zchrissirhcz 非常感谢，已经合入。不过我理解 @piaobuliao 在这个 Issue 里想要的不是在 Windows 上交叉编译 Android lib，而是想在 Windows 上编译一个 Windows dll 类似的东东。:)

**Comment by piaobuliao** [comment]
@solrex 对的,我只是编译一个caffe的dll
