### ISSUE TITLE
NDK_HOME

### ISSUE THREAD

**Issue by zhangfucheng** [solrex/caffe-mobile#18]
I want recurrent this project,meet a basic problem about NDK_HOME
I have set $NDK_HOME   in ./bashrc file,and test $NDK_HOME/ndk_build is ok!
but yet have error:

:###########################################################
 ERROR: Invalid NDK_HOME="" env variable, exit. 
###########################################################

my NDK is loaded from government website, https://developer.android.google.cn/ndk/downloads/index.html
how about solve this error?

Thanks

**Comment by solrex** [comment]
@zhangfucheng How did you "set NDK_HOME" in  .bashrc? You should `export NDK_HOME=something` in .bashrc, instead of just let `NDK_HOME=something` in .bashrc.

**Comment by zhangfucheng** [comment]
Yes,I actually add "export NDK_HOME=yourpath" into .bashrc,
 and in Terminal test then show:  $NDK_HOME
bash:yourpath,
but, failed

**Comment by solrex** [comment]
@zhangfucheng Sorry, I cannot reproduce your problem. Perhaps running the script in a clean bash environment (i.e. empty .bashrc/.bashprofile) may help.
