### ISSUE TITLE
Could not find PROTOBUF Compiler on MacOS Sierra 10.12

### ISSUE THREAD

**Issue by iphone5solo** [solrex/caffe-mobile#19]
Hi, @solrex 
I want to run the Demo on iPhone Simulator, But when I do it 
`cmake .. -DCMAKE_TOOLCHAIN_FILE=../third_party/ios-cmake/toolchain/iOS.cmake   -DIOS_PLATFORM=SIMULATOR -DTHIRD_PARTY=1`

I get this error:

```
CMake Warning (dev) at third_party/ios-cmake/toolchain/iOS.cmake:155 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "SIMULATOR" will no longer be dereferenced when the
  policy is set to NEW.  Since the policy is not set the OLD behavior will be
  used.
Call Stack (most recent call first):
  build/CMakeFiles/3.8.2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at /usr/local/Cellar/cmake/3.8.2/share/cmake/Modules/FindProtobuf.cmake:387 (message):
  Protobuf compiler version doesn't match library version 3.1.0
Call Stack (most recent call first):
  cmake/ProtoBuf.cmake:4 (find_package)
  CMakeLists.txt:41 (include)


CMake Error at cmake/ProtoBuf.cmake:13 (message):
  Could not find PROTOBUF Compiler
Call Stack (most recent call first):
  CMakeLists.txt:41 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/mambaxie/Desktop/DeapLeaning/caffe-mobile/build/CMakeFiles/CMakeOutput.log".

```

How can I fix it?

**Comment by solrex** [comment]
@iphone5solo Notice this warning:

`Protobuf compiler version doesn't match library version 3.1.0.`

It means you have installed another version of protobuf in your system path. Please check `which protoc`, remove it (with headers and libs) if needed.

**Comment by iphone5solo** [comment]
我的就是3.1.0 ，可以加一下QQ么，有一些事比较好沟通，好高兴您能回复我！我的QQ是499491531

**Comment by mekex2** [comment]
Hi, @solrex
Even though protoc version is 3.1.0, I get the same error.
```
$ protoc --version
libprotoc 3.1.0
```

Protoc3.1.0 installed with Homebrew using its version commit. 
```
$ git checkout 564a3f2c5c3757d3de5a24fbfcd29d4e0444352c protobuf.rb
$ brew install protobuf
```
And there is no other version of protoc.
Are there any possible causes?

Thank you.

**Comment by solrex** [comment]
@mekex2 Don't know why. You can remove the brew installed protobuf, use the third_party one instead.

**Comment by solrex** [comment]
@iphone5solo 你可以在知乎上找到我，我的知乎 ID 和 github 一样 [solrex](https://www.zhihu.com/people/solrex)
