### ISSUE TITLE
xcode compile errors

### ISSUE THREAD

**Issue by huzhenbang** [solrex/caffe-mobile#21]
errors information is "ld: warning: ignoring file ../../../build/lib/libcaffe.a, missing required architecture i386 in file ../../../build/lib/libcaffe.a (3 slices)"
The library can not be loaded correct. Help please.

**Comment by solrex** [comment]
@huzhenbang If it needs i386 arch, that means you were building for simulator. Please follow the building instructions for *iPhone Simulator*.
