### ISSUE TITLE
可以运行FCN吗

### ISSUE THREAD

**Issue by daimagou** [solrex/caffe-mobile#22]
Hi 博主好，感谢提供demo，想请教一个问题，就是基于你这个框架，可以移植跑FCN吗？

**Comment by solrex** [comment]
@daimagou 这取决于你能否用 Caffe 实现 FCN。

**Comment by daimagou** [comment]
你好，我编译好好jni的库，caffe的库，和apk,在打开app的时候，直接crash了，log如下：
03-17 05:09:09.507 25249 25249 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/test_image.jpg: open failed: ENOENT (No such file or directory)
03-17 05:09:09.509 25249 25249 D MainActivity: onCreate: modelFile:/storage/emulated/0/net.protobin
03-17 05:09:09.509 25249 25249 D MainActivity: onCreate: weightFIle:/storage/emulated/0/weight.caffemodel
03-17 05:09:09.510 25249 25249 I caffe   : ERROR /caffe-mobile/src/caffe/util/io.cpp:72] (fd) != (-1) File not found: /storage/emulated/0/net.protobin
03-17 05:09:09.510 25249 25249 I caffe   : ERROR /caffe-mobile/src/caffe/util/io.cpp:72] (fd) != (-1) File not found: /storage/emulated/0/weight.caffemodel
03-17 05:09:09.510 25249 25249 I caffe   : INFO /caffe-mobile/src/jni/caffe_mobile.cpp:34] Load (/storage/emulated/0/net.protobin,/storage/emulated/0/weight.caffemodel), time:0
.422 ms.
03-17 05:09:09.510 25249 25249 I caffe   : ERROR /caffe-mobile/src/jni/caffe_mobile.cpp:37] (net_->num_inputs()) == (1) Network should have exactly one input.
03-17 05:09:09.510 25249 25249 I caffe   : ERROR /caffe-mobile/src/jni/caffe_mobile.cpp:38] (net_->num_outputs()) == (1) Network should have exactly one output.
--------- beginning of crash
03-17 05:09:09.510 25249 25249 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 25249 (nbo.caffesimple)
03-17 05:09:09.561   536   536 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-17 05:09:09.561   536   536 F DEBUG   : Build fingerprint: 'LYF/LS-5201/panda01a_msm8952_64:6.0.1/MMB29M/195:user/release-keys'
03-17 05:09:09.561   536   536 F DEBUG   : Revision: '0'
03-17 05:09:09.561   536   536 F DEBUG   : ABI: 'arm64'
03-17 05:09:09.562   536   536 F DEBUG   : pid: 25249, tid: 25249, name: nbo.caffesimple  >>> com.yangwenbo.caffesimple <<<
03-17 05:09:09.562   536   536 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
03-17 05:09:09.568   536   536 F DEBUG   :     x0   0000000000000000  x1   0000000000000010  x2   0000000000000000  x3   0000007f97b685a0
03-17 05:09:09.568   536   536 F DEBUG   :     x4   0000007f97b68618  x5   0000000000000001  x6   0000000000000000  x7   0000000000000000
03-17 05:09:09.568   536   536 F DEBUG   :     x8   00000000000012d1  x9   0000007f9c2e8a70  x10  0000000000000003  x11  0000007f991a9000
03-17 05:09:09.568   536   536 F DEBUG   :     x12  0000007f9c2e8a70  x13  00000055a4680a60  x14  00000055a44e7b20  x15  0000000000000000
03-17 05:09:09.568   536   536 F DEBUG   :     x16  0000007f9c2e1a58  x17  0000000000000000  x18  0000007f991a9000  x19  0000007ff7474bc8
03-17 05:09:09.568   536   536 F DEBUG   :     x20  0000007ff7474bd8  x21  0000007ff74748a0  x22  0000007f97ad6f10  x23  0000007f97ad6f30
03-17 05:09:09.568   536   536 F DEBUG   :     x24  0000007f97b68618  x25  0000007f97b68550  x26  0000007ff7474bd8  x27  0000007f97b68578
03-17 05:09:09.568   536   536 F DEBUG   :     x28  0000007f97b68528  x29  0000000012dad680  x30  0000007f978ca5b0
03-17 05:09:09.568   536   536 F DEBUG   :     sp   0000007ff7474800  pc   0000007f978ca5bc  pstate 0000000020000000
03-17 05:09:09.570   536   536 F DEBUG   :
03-17 05:09:09.570   536   536 F DEBUG   : backtrace:
03-17 05:09:09.570   536   536 F DEBUG   :     #00 pc 00000000000dd5bc  /data/app/com.yangwenbo.caffesimple-1/lib/arm64/libcaffe-jni.so (_ZN5caffe11CaffeMobileC1ERKSsS2_+2380)
03-17 05:09:09.570   536   536 F DEBUG   :     #01 pc 00000000000df7d4  /data/app/com.yangwenbo.caffesimple-1/lib/arm64/libcaffe-jni.so (_ZN5caffe11CaffeMobile3getERKSsS2_+84)
03-17 05:09:09.570   536   536 F DEBUG   :     #02 pc 00000000000d7754  /data/app/com.yangwenbo.caffesimple-1/lib/arm64/libcaffe-jni.so (Java_com_yangwenbo_caffemobile_CaffeMobile_loadModel+
136)
03-17 05:09:09.570   536   536 F DEBUG   :     #03 pc 0000000000535c64  /data/app/com.yangwenbo.caffesimple-1/oat/arm64/base.odex (offset 0x32c000) (boolean com.yangwenbo.caffemobile.CaffeMo
bile.loadModel(java.lang.String, java.lang.String)+184)
03-17 05:09:09.570   536   536 F DEBUG   :     #04 pc 000000000070a5d0  /data/app/com.yangwenbo.caffesimple-1/oat/arm64/base.odex (offset 0x32c000) (void com.yangwenbo.caffesimple.MainActivi
ty.onCreate(android.os.Bundle)+2324)
03-17 05:09:09.570   536   536 F DEBUG   :     #05 pc 0000000002992a68  /system/framework/arm64/boot.oat (offset 0x1f03000)
03-17 05:09:09.651  1261 25269 W ActivityManager:   Force finishing activity com.yangwenbo.caffesimple/.MainActivity

能否帮忙分析下原因，caffemodel  prototxt  和测试图片均push进去的，从log看是读取这三个文件失败了，但是，下面又有load花费了多少时间的log，所以，不清楚究竟load成功没有，谢谢

**Comment by solrex** [comment]
@daimagou 你的错误的确是这三个文件没找到。你可以检查一下自己的SD卡根目录，看看有没有这三个文件。之所以没有直接停下来，应该是没处理文件加载失败的异常，继续的时候才crash了。

**Comment by daimagou** [comment]
最后发现，是APP没有申请权限，手动去权限里面把访问SD卡打开，就OK了，谢谢。

**Comment by actionLUO** [comment]
@daimagou 请问您的fcn移植成功了吗？是否方便交流一下？
