### ISSUE TITLE
import caffe failed

### ISSUE THREAD

**Issue by jessica025** [solrex/caffe-mobile#23]
when I use prototxt2bin.py, get the error message
![image](https://user-images.githubusercontent.com/31124642/29448258-48641756-8428-11e7-88ae-6472f8bf94d6.png)

Do I have to install Caffe first?

**Comment by daimagou** [comment]
你到caffe/python目录下去就可以

**Comment by solrex** [comment]
@jessica025 Yes, it's a simpler way.
