### ISSUE TITLE
Flasback after loading CaffeSample on Android phone

### ISSUE THREAD

**Issue by dyt001** [solrex/caffe-mobile#25]
Everything is fine with the android build step. And I changed the batch size setting in net.prototxt before push it to sdcard. But when run app on the android phone, it always flashback to the home page.  Do I missed any point?

**Comment by dyt001** [comment]
![screenshot from 2017-08-29 12 57 28](https://user-images.githubusercontent.com/12581687/29833557-cf21a486-8cb9-11e7-864e-16f9f33ed27e.png)
Error occured like this.

**Comment by solrex** [comment]
@dyt001 You need to push `net.protobin` to sd card instead of `net.prototxt`. Read the README.md through again.

**Comment by dyt001** [comment]
That works. Thank you!
