### ISSUE TITLE
How to build .so file for android emulator (x86)

### ISSUE THREAD

**Issue by rizkyario** [solrex/caffe-mobile#28]
Hello @solrex, would it be possible to build libcaffe-jni.so for x86 as well so it can run on android emulator?

**Comment by solrex** [comment]
@rizkyario It is possible but not very helpful. Most of the people use arm ABIs both on the emulator and the real device.

**Comment by Aki92** [comment]
@solrex @rizky  It'll be really great if you can help me with the **.so file for arm64-v8a** as with new Google Play Store guidelines we need to make our app compatible with both 32 & 64-bit versions & w/o .so files for 64 bit I'm unable to update my app.

**Comment by solrex** [comment]
@Aki92 Is it what you need? https://github.com/solrex/caffe-mobile/releases/tag/1.0
