### ISSUE TITLE
Add new layer in caffe on iOS

### ISSUE THREAD

**Issue by HaiPhan1991** [solrex/caffe-mobile#29]
Hi @solrex ,

Thank for you great work. I have a problem in runtime. I add a new layer and revise caffe.proto with parameters but the library can not recognize these parameters. I convert prototxt into protobin. How can you add a new layer?

Here is example:

Caffe.proto:
message NewLayerParameter {
  optional uint32 num_classes = 1;
  optional bool share_location = 2 [default = true];
}

prototxt:
layer {
  name: "out"
  type: "NewLayer"
  bottom: "data"
  top: "out"
  include {
    phase: TEST
  }
  output_param {
    num_classes: 2
    share_location: true
 }
}

The program does not know num_classes = 2 and share_location = true.

Thanks.

**Comment by solrex** [comment]
@HaiPhan1991 You should add NewLayerParameter both to caffe-mobile/src/caffe/proto/caffe.proto and caffe/src/caffe/proto/caffe.proto. These two files are almost the same but have subtle differences. Then rebuild caffe for PC, and caffe-mobile for mobile devices.

**Comment by HaiPhan1991** [comment]
Hi, 
I did both mobile device and PC. I have already used PC for generating the protobin file and log out paramters in runtime of c++, but it did not work. Could you try checking it? 
Btw, I solved it by replacing proto file and add my new layer,  it works now.

**Comment by solrex** [comment]
@HaiPhan1991 Sorry for not getting your idea. Maybe it was the build issue, like you need to clean up and rebuild the generated pb files. No matter what, I'm glad to hear that you've already solved it. Cheers!
