### ISSUE TITLE
"./build-protobuf-3.1.0.sh iPhoneOS" compile with error "No iOS SDK's found in default search path .  Manually set   CMAKE_IOS_SDK_ROOT or install the iOS SDK."

### ISSUE THREAD

**Issue by zhaoxiangyulove** [solrex/caffe-mobile#3]
error log:
CMake Error at /Users/zhaoxiangyu/Documents/caffe-mobile/third_party/ios-cmake/toolchain/iOS.cmake:143 (message):
  No iOS SDK's found in default search path .  Manually set
  CMAKE_IOS_SDK_ROOT or install the iOS SDK.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/CMakeDetermineSystem.cmake:85 (include)
  CMakeLists.txt:12 (project)
pls tell me how to fix it! thx!

**Comment by solrex** [comment]
Do you have Xcode installed？

Normally you can find your iOS SDKs in /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/.

**Comment by zhaoxiangyulove** [comment]
Thanks for helping me！
I Did install Xcode 8.0 ,and find iOS SDKs in that path.
When I run "./build-protobuf-3.1.0.sh iPhoneOS" ,it is still not working!
here are All logs:
bogon:third_party zhaoxiangyu$ ./build-protobuf-3.1.0.sh iPhoneOS
Building Google Protobuf for iPhoneOS
##########################################
 Fetch Google Protobuf 3.1.0 from source.
##########################################

#####################
 Building protobuf for iPhoneOS
#####################

CMake Error at /Users/zhaoxiangyu/Documents/caffe-mobile/third_party/ios-cmake/toolchain/iOS.cmake:143 (message):
  No iOS SDK's found in default search path .  Manually set
  CMAKE_IOS_SDK_ROOT or install the iOS SDK.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/CMakeDetermineSystem.cmake:85 (include)
  CMakeLists.txt:12 (project)

-- Configuring incomplete, errors occurred!
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.


Maybe I write wrong? Trouble you to help！

**Comment by solrex** [comment]
The default search path is determined by command `/usr/bin/xcode-select -p`. It prints `/Applications/Xcode.app/Contents/Developer` on my Mac. You can check if this command outputs the right thing.

Moreover, you can manually set CMAKE_IOS_SDK_ROOT yourself. Open `build-protobuf-3.1.0.sh`, find line 181 (the `cmake *` line in function `build-iPhoneOS`). Then add a `-DCMAKE_IOS_SDK_ROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer` to cmake options as bellow:

    cmake ../cmake -DCMAKE_INSTALL_PREFIX=../../protobuf-$TARGET\
        -DCMAKE_TOOLCHAIN_FILE="../../ios-cmake/toolchain/iOS.cmake" \
        -DCMAKE_IOS_SDK_ROOT="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer" \
        -DIOS_PLATFORM=OS \
        -DCMAKE_CXX_FLAGS="-fembed-bitcode" \
        -Dprotobuf_BUILD_TESTS=OFF \
        -Dprotobuf_BUILD_SHARED_LIBS=OFF \
        -Dprotobuf_WITH_ZLIB=OFF

**Comment by zhaoxiangyulove** [comment]
OK！It works！Thank you~~~
