### ISSUE TITLE
can not compiling without connecting to internet

### ISSUE THREAD

**Issue by wakeee** [solrex/caffe-mobile#30]
could you please put all the dependencies into the project?

**Comment by solrex** [comment]
@wakeee The downloading is only needed for the first time. Put protobuf & openblas in git repository is too large.

**Comment by wakeee** [comment]
could you please write some words to explain which libs  to dependent  and how to  put the zip files on the right place?

**Comment by solrex** [comment]
@wakeee I guess you are not familiar with shell script. Running with command "bash -x *.sh" (or add "set -x" to the first line of *.sh file) can print out every expanded command in the script. You will find the expanded "curl" command with real url and target file name.

For your convenience, you should download these files to "third_party" directory:

curl -L https://github.com/google/protobuf/archive/v3.1.0.tar.gz --output protobuf-3.1.0.tar.gz
curl -L https://github.com/xianyi/OpenBLAS/archive/v0.2.19.tar.gz --output OpenBLAS-0.2.19.tar.gz
curl -L https://github.com/xianyi/OpenBLAS/archive/arm_soft_fp_abi.zip --output OpenBLAS-arm_soft_fp_abi.zip
