### ISSUE TITLE
Build Error on Mac

### ISSUE THREAD

**Issue by tchen7** [solrex/caffe-mobile#31]
Hi, 
    Anyone had the same problem?
    ERROR: "Could not find PROTOBUF Compiler"
    Tried reinstall protobuf on Mac, not helping.
    I don't have Caffe on my Mac, could this be the problem?

**Comment by solrex** [comment]
@tchen7 Sorry. I made some changes recently in commit https://github.com/solrex/caffe-mobile/commit/4d43d23cc236aa6bec62a36abdb32330667eb84a. But not tested on Mac.  Could you please try git checkout 0a8a8bd013b7883cedf690523e799799bd722ea0 and see if it is right? Thank you!

**Comment by solrex** [comment]
@tchen7 I already fixed the bug so this issue is closed. Thank you very much for your report.
