### ISSUE TITLE
ios上编caffesimple的项目出现google::protobuf的错误

### ISSUE THREAD

**Issue by xujinchang** [solrex/caffe-mobile#32]
你好,在mac上可以编译通过,生成libcaffe.a 和libproto.a, 但是在ios上编你的caffesimple的项目的时候,使用你的Xcode配置,只不过把ios 系统从10.3降到9.3, 然后报一堆类似这样的错,我只粘了部分,希望您能解答一下
Undefined symbols for architecture arm64:
  "google::protobuf::io::CodedInputStream::default_recursion_limit_", referenced from:
      caffe::ReadProtoFromBinaryFile(char const*, google::protobuf::MessageLite*) in libcaffe.a(io.cpp.o)
  "google::protobuf::io::CodedInputStream::Refresh()", referenced from:
      caffe::ReadProtoFromBinaryFile(char const*, google::protobuf::MessageLite*) in libcaffe.a(io.cpp.o)
  "typeinfo for google::protobuf::io::CopyingInputStream", referenced from:
      typeinfo for caffe::ReadProtoFromBinaryFile(char const*, google::protobuf::MessageLite*)::CopyingFileInputStream in libcaffe.a(io.cpp.o)
  "google::protobuf::MessageLite::ParseFromCodedStream(google::protobuf::io::CodedInputStream*)", referenced from:
      caffe::ReadProtoFromBinaryFile(char const*, google::protobuf::MessageLite*) in libcaffe.a(io.cpp.o)
  "google::protobuf::io::CodedInputStream::~CodedInputStream()", referenced from:
      caffe::ReadProtoFromBinaryFile(char const*, google::protobuf::MessageLite*) in libcaffe.a(io.cpp.o)
  "google::protobuf::io::CopyingInputStream::Skip(int)", referenced from:
      vtable for caffe::ReadProtoFromBinaryFile(char const*, google::protobuf::MessageLite*)::CopyingFileInputStream in libcaffe.a(io.cpp.o)
  "google::protobuf::MessageLite::InitializationErrorString() const", referenced from:
      vtable for caffe::BlobShape in libproto.a(caffe.pb.cc.o)
      vtable for caffe::BlobProto in libproto.a(caffe.pb.cc.o)
      vtable for caffe::BlobProtoVector in libproto.a(caffe.pb.cc.o)
      vtable for caffe::Datum in libproto.a(caffe.pb.cc.o)
      vtable for caffe::FillerParameter in libproto.a(caffe.pb.cc.o)
      vtable for caffe::NetParameter in libproto.a(caffe.pb.cc.o)
      vtable for caffe::SolverParameter in libproto.a(caffe.pb.cc.o)
      ...
  "google::protobuf::MessageLite::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const", referenced from:
      vtable for caffe::BlobShape in libproto.a(caffe.pb.cc.o)
      vtable for caffe::BlobProto in libproto.a(caffe.pb.cc.o)
      vtable for caffe::BlobProtoVector in libproto.a(caffe.pb.cc.o)
      vtable for caffe::Datum in libproto.a(caffe.pb.cc.o)
      vtable for caffe::FillerParameter in libproto.a(caffe.pb.cc.o)
      vtable for caffe::NetParameter in libproto.a(caffe.pb.cc.o)
      vtable for caffe::SolverParameter in libproto.a(caffe.pb.cc.o)
      ...
  "google::protobuf::internal::LogMessage::operator<<(char const*)", referenced from:
      google::protobuf::RepeatedField<float>::Reserve(int) in libproto.a(caffe.pb.cc.o)
      google::protobuf::RepeatedField<double>::Reserve(int) in libproto.a(caffe.pb.cc.o)
      google::protobuf::RepeatedField<int>::Reserve(int) in libproto.a(caffe.pb.cc.o)
      google::protobuf::RepeatedField<long long>::Reserve(int) in libproto.a(caffe.pb.cc.o)
      google::protobuf::RepeatedField<bool>::Reserve(int) in libproto.a(caffe.pb.cc.o)
      google::protobuf::RepeatedField<unsigned int>::Reserve(int) in libproto.a(caffe.pb.cc.o)
      google::protobuf::RepeatedField<long long>::Reserve(int) in libcaffe.a(blob.cpp.o)
      ...
  "google::protobuf::internal::LogFinisher::operator=(google::protobuf::internal::LogMessage&)", referenced from:
      google::protobuf::RepeatedField<float>::Reserve(int) in libproto.a(caffe.pb.cc.o)
      google::protobuf::RepeatedField<double>::Reserve(int) in libproto.a(caffe.pb.cc.o)
      google::protobuf::RepeatedField<int>::Reserve(int) in libproto.a(caffe.pb.cc.o)
      google::protobuf::RepeatedField<long long>::Reserve(int) in libproto.a(caffe.pb.cc.o)
      google::protobuf::RepeatedField<bool>::Reserve(int) in libproto.a(caffe.pb.cc.o)
      google::protobuf::RepeatedField<unsigned int>::Reserve(int) in libproto.a(caffe.pb.cc.o)
      google::protobuf::RepeatedField<long long>::Reserve(int) in libcaffe.a(blob.cpp.o)

**Comment by xujinchang** [comment]
但是,我在iphone 虚拟机的环境下,编译是success的,没有出现这些错误....

**Comment by solrex** [comment]
@xujinchang 你仔细看一下 README，iPhone 虚拟机和 iPhone 物理机是不同的编译依赖。iPhone 虚拟机只需要 x86 的 .a，iPhone 物理机是需要 arm 三个架构的 .a 打包成最终的 .a。我目前提供的编译环境，是不支持同时进行真机和物理机的开发的。

**Comment by xujinchang** [comment]
@solrex 很感谢您的答复，我是按照README做的，因为一开始在真机上编译的caffesimple项目出现上面的问题，所以我又按照iphone虚拟机的操作编译的，结果显示虚拟机上可以成功运行，真机上出现上面的错误。

**Comment by solrex** [comment]
@xujinchang 可能是我调整了编译目录导致的，我今天更新了一下，你再试试？
