### ISSUE TITLE
关于增加新的自定义层

### ISSUE THREAD

**Issue by zt383154** [solrex/caffe-mobile#33]
请问是否支持自己增加新的层，增加新的层编译配置方面需要修改吗。 @solrex

**Comment by solrex** [comment]
@zt383154 如果是简单的层，只需要在 caffe.proto 里把对应层的配置加上，然后把对应层 CPU 前向计算放到该在的位置上即可。你可以diff一下跟你的层类似的原生层的实现，在 caffe-mobile 中和 caffe 中有什么不同。一般来说，大部分纯计算的层没有任何不同，有依赖的层要检查一下依赖是否满足（比如是否依赖hdf5之类）。

**Comment by zt383154** [comment]
好的，我的自定义层是纯数据的，不依赖第三方库。 @solrex

**Comment by solrex** [comment]
@zt383154 我先 close 了，如果遇到问题，可以过来留言再 reopen。

**Comment by liminglu** [comment]
你好，我打开HDF5宏之后，编译可以成功，但链接到CaffeSimple项目中，报符号找不到
