### ISSUE TITLE
device_alternate.hpp:34:23: fatal error: cublas_v2.h: No such file or directory 

### ISSUE THREAD

**Issue by YangBowenn** [solrex/caffe-mobile#36]
When I ndk-build classification.cpp with libcaffe.a and other dependences, I get the error as above. Do you know why? Is this project build at CPU_only？

**Comment by solrex** [comment]
@YangBowenn Cublas is a CUDA library. You cannot use it on a mobile device. Thus it is not supported.

**Comment by YangBowenn** [comment]
感谢答复，我可能没有把问题说清楚，我按照您工程中android对应的流程，生成了libcaffe.a等静态库和动态库，这个生成的应该是cpu模式的吧，为什么使用ndk编译时还会报找不到cublas库的错误呢？

**Comment by solrex** [comment]
@YangBowenn 你编译 classification 时，需要参考 caffe-mobile 的 CMakeList.txt，传入对应的预编译宏，才能在预处理中过滤掉相应部分的代码。

**Comment by YangBowenn** [comment]
请问在哪里可以开启caffei-mobile的android版本对opencv3的支持？

**Comment by solrex** [comment]
@YangBowenn 你需要自己编译 OpenCV 的 Android 库，然后编译 caffe-mobile 时传入 OpenCV 头文件路径和库路径，并 add_definitions(-DUSE_OPENCV)。但是我没有测试过是否可行，祝你好运。

**Comment by actionLUO** [comment]
@YangBowenn 您好，请问您加入opencv了吗？方便讨论吗？
