### ISSUE TITLE
fatal error: glog/logging.h: No such file or directory

### ISSUE THREAD

**Issue by cxy200927099** [solrex/caffe-mobile#37]
楼主你好--我这边新添加的一些层，头文件中用到了glog
我是mac的系统，这个问题网上说是没有安装glog，可是我已经安装了
通过brew install 和 conda install 都安装了 glog，可编译的时候还是报错，请问下有遇到过这种问题吗？

**Comment by solrex** [comment]
@cxy200927099 为了缩减包大小，我自己实现了 glog 的接口，如果你只是想打些日志，请 include caffe/glog_wrapper.hpp

**Comment by cxy200927099** [comment]
@solrex 嗯，我已经注释掉glog的库了，但是我们用到了一些boost 相关的接口，
```
#include "boost/iterator/counting_iterator.hpp"
```
想问下楼主是不是需要成功编译过了caffe，才能正确的引入这类的头文件？

因为我是在mac上测试，我正在做一些移植性的工作，在AI这块都是新手，mac上的环境一直弄不好，网上查了好久了，貌似很多人也遇到mac上编译报错的问题，但是一直没有解决方案；

**Comment by solrex** [comment]
@cxy200927099 为了精简大小，我没有引入 boost 库。你可以考虑一下自己解决 boost 库的引入问题。

**Comment by cxy200927099** [comment]
@solrex 好的，多谢楼主指教，赞一个👍👍👍，对了楼主有没有qq群什么的，方便大家交流！
楼主可以关闭这个issue了，谢谢！

**Comment by solrex** [comment]
@cxy200927099 在这里讨论就挺好的 ^_^
