### ISSUE TITLE
error: thread-local storage is not supported for the current target

### ISSUE THREAD

**Issue by lucwan** [solrex/caffe-mobile#38]
-- Build files have been written to: /Users/nitinjindal/Desktop/mobilecaffe/caffe-mobile/build_iPhoneSimulator
[  1%] Running C++/Python protocol buffer compiler on /Users/nitinjindal/Desktop/mobilecaffe/caffe-mobile/src/caffe/proto/caffe.proto
Scanning dependencies of target proto
[  3%] Building CXX object src/caffe/CMakeFiles/proto.dir/__/__/include/caffe/proto/caffe.pb.cc.o
[  4%] Linking CXX static library ../../lib/libproto.a
[  4%] Built target proto
Scanning dependencies of target caffe
[  9%] Building CXX object src/caffe/CMakeFiles/caffe.dir/blob.cpp.o
[  9%] Building CXX object src/caffe/CMakeFiles/caffe.dir/data_transformer.cpp.o
[  9%] Building CXX object src/caffe/CMakeFiles/caffe.dir/common.cpp.o
[ 10%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layer_factory.cpp.o
/Users/nitinjindal/Desktop/mobilecaffe/caffe-mobile/src/caffe/common.cpp:24:1: error: thread-local storage is not supported for the current target
thread_local static Caffe *thread_instance_ = NULL;
^
1 error generated.
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/common.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2

**Comment by solrex** [comment]
@lucwan Could you please provide more information? It seems like your C++ compiler does not support C++11.
