### ISSUE TITLE
编译完成后在Android上加载模型出现以下错误，请问是什么情况？

### ISSUE THREAD

**Issue by Qvodman** [solrex/caffe-mobile#39]
01-05 14:30:56.275 21070-21070/com.meiya.sy.caffedemo D/MainActivity: onCreate: modelFile:/storage/emulated/0/descriptor
01-05 14:30:56.275 21070-21070/com.meiya.sy.caffedemo D/MainActivity: onCreate: weightFIle:/storage/emulated/0/sexy20171208_iter_1110.caffemodel
01-05 14:30:57.607 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/util/upgrade_proto.cpp:77] Attempting to upgrade batch norm layers using deprecated params: /storage/emulated/0/sexy20171208_iter_1110.caffemodel
01-05 14:30:57.608 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/util/upgrade_proto.cpp:80] Successfully upgraded batch norm layers using deprecated params.
01-05 14:30:57.609 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer data
01-05 14:30:57.609 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv1a
01-05 14:30:57.609 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv1a_bn
01-05 14:30:57.609 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv1a_scale
01-05 14:30:57.609 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu1a
01-05 14:30:57.609 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv1b
01-05 14:30:57.609 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv1b_bn
01-05 14:30:57.609 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv1b_scale
01-05 14:30:57.609 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu1b
01-05 14:30:57.609 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer pool1b
01-05 14:30:57.610 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer pool1b_pool1b_0_split
01-05 14:30:57.610 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv2_1
01-05 14:30:57.610 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv2_1_bn
01-05 14:30:57.610 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv2_1_scale
01-05 14:30:57.610 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu2_1
01-05 14:30:57.610 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv2_2
01-05 14:30:57.610 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv2_2_bn
01-05 14:30:57.610 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv2_2_scale
01-05 14:30:57.610 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu2_2
01-05 14:30:57.610 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer res2_2
01-05 14:30:57.610 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv2
01-05 14:30:57.610 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv2_bn
01-05 14:30:57.610 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv2_scale
01-05 14:30:57.610 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu2
01-05 14:30:57.610 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer pool2
01-05 14:30:57.610 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer pool2_pool2_0_split
01-05 14:30:57.610 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv3_1
01-05 14:30:57.610 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv3_1_bn
01-05 14:30:57.610 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv3_1_scale
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu3_1
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv3_2
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv3_2_bn
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv3_2_scale
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu3_2
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer res3_2
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer res3_2_res3_2_0_split
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv3_3
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv3_3_bn
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv3_3_scale
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu3_3
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv3_4
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv3_4_bn
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv3_4_scale
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu3_4
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer res3_4
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv3
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv3_bn
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv3_scale
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu3
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer pool3
01-05 14:30:57.611 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer pool3_pool3_0_split
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_1
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_1_bn
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_1_scale
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu4_1
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_2
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_2_bn
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_2_scale
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu4_2
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer res4_2
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer res4_2_res4_2_0_split
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_3
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_3_bn
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_3_scale
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu4_3
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_4
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_4_bn
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_4_scale
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu4_4
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer res4_4
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer res4_4_res4_4_0_split
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_5
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_5_bn
01-05 14:30:57.612 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_5_scale
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu4_5
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_6
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_6_bn
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_6_scale
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu4_6
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer res4_6
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer res4_6_res4_6_0_split
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_7
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_7_bn
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_7_scale
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu4_7
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_8
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_8_bn
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_8_scale
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu4_8
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer res4_8
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer res4_8_res4_8_0_split
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_9
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_9_bn
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_9_scale
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu4_9
01-05 14:30:57.613 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_10
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_10_bn
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_10_scale
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu4_10
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer res4_10
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_bn
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv4_scale
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu4
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer pool4
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer pool4_pool4_0_split
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv5_1
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv5_1_bn
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv5_1_scale
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu5_1
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv5_2
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv5_2_bn
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv5_2_scale
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu5_2
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer res5_2
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer res5_2_res5_2_0_split
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv5_3
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv5_3_bn
01-05 14:30:57.614 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv5_3_scale
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu5_3
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv5_4
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv5_4_bn
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv5_4_scale
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu5_4
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer res5_4
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer res5_4_res5_4_0_split
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv5_5
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv5_5_bn
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv5_5_scale
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu5_5
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv5_6
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv5_6_bn
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer conv5_6_scale
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer relu5_6
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer res5_6
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer fc6
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer fc6_bn
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer fc6_scale
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer fc6_fc6_scale_0_split
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer sample_triplet
01-05 14:30:57.615 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer triplet_loss
01-05 14:30:57.616 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer L2length
01-05 14:30:57.616 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/caffe/net.cpp:765] Ignoring source layer mean_length
01-05 14:30:57.638 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/jni/caffe_mobile.cpp:34] Load (/storage/emulated/0/descriptor,/storage/emulated/0/sexy20171208_iter_1110.caffemodel), time:1359.55 ms.
01-05 14:30:57.639 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/jni/caffe_mobile.cpp:37] num_input:0
01-05 14:30:57.639 21070-21070/com.meiya.sy.caffedemo I/caffe: INFO /home/liaolp/caffe-mobile/src/jni/caffe_mobile.cpp:38] num_output:0
01-05 14:30:57.642 21070-21070/com.meiya.sy.caffedemo A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 21070 (ya.sy.caffedemo)
                                                              
                                                              [ 01-05 14:30:57.643   407:  407 W/         ]
                                                              debuggerd: handling request: pid=21070 uid=10392 gid=10392 tid=21070

**Comment by solrex** [comment]
@Qvodman 看起来是没有载入对应的网络配置 .protobin 文件

**Comment by Qvodman** [comment]
不是吧，在PC上是能跑的

**Comment by Qvodman** [comment]
@solrex 不是吧，在PC上是能跑的

**Comment by solrex** [comment]
@Qvodman /storage/emulated/0/descriptor 这是个文件吗？是用 .prototxt 转成的 .protobin 格式吗？

**Comment by Qvodman** [comment]
@solrex descriptor这是.prototxt文件，这个框架要转成.protobin才能跑起来吗？请问要怎么转？

**Comment by solrex** [comment]
@Qvodman 首页有写：If you want to use your self-defined caffe network, use tools/prototxt2bin.py net.prototxt to convert your prototxt to protobin. Then push net.protobin to your sdcard root directory.
