### ISSUE TITLE
caffe::Net<float> *_net cann't use "Reshape()" method

### ISSUE THREAD

**Issue by zhaoxiangyulove** [solrex/caffe-mobile#4]
hi @solrex ,it's me!
When I use the example of iOS,I try to use _net to call "Reshape()",it will be error with logs:
Undefined symbols for architecture arm64:
  "caffe::Net<float>::Reshape()", referenced from:
      -[ViewController RunCaffeModel:] in ViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
I don't know how to fix it. Maybe libcaffe.a not contain net.cpp?
May you share how to build caffe for iOS?

**Comment by solrex** [comment]
Sorry. It was my mistake to commented caffe::Net::Reshape() function out. `git pull` and rebuild plz.
