### ISSUE TITLE
predict问题

### ISSUE THREAD

**Issue by Qvodman** [solrex/caffe-mobile#40]
为何用我自己的模型使用predict(byte[] bitmap, int channels, float[]mean)方法提到的特征和在PC上提到的特征差很多？

**Comment by solrex** [comment]
@Qvodman 首先检查一下输入的图片 bitmap 矩阵，是否与 PC 上的矩阵一致。此外就是精度问题，因为ALU实现和精度不同，理论上肯定是存在误差的，但是差多少还得看经验。

**Comment by Qvodman** [comment]
@solrex 之后会改用opencv读取图片吗？

**Comment by solrex** [comment]
@Qvodman 直接集成 OpenCV 库会比较大，你可以考虑自己集成。
