### ISSUE TITLE
prototxt

### ISSUE THREAD

**Issue by wangli07115** [solrex/caffe-mobile#42]
1,  this project  don't  support net.prototxt?

2,[use tools/prototxt2bin.py net.prototxt to convert your prototxt to protobin]
but  this project not make for python

**Comment by solrex** [comment]
@wangli07115 prototxt2bin.py only depends on caffe_pb2. It is generated by `protoc` so there is no need for other step.

**Comment by wangli07115** [comment]
@solrex 直接运行链接不到from google.protobuf import text_format。

**Comment by wangli07115** [comment]
好了。sudo pip install protobuf。
