### ISSUE TITLE
能集成opencv么？

### ISSUE THREAD

**Issue by rochou** [solrex/caffe-mobile#46]
楼主，能一起集成下opencv么？非常感谢，刚学这一块，实在不知道怎么交叉编译opencv相关部分

**Comment by solrex** [comment]
@rochou 抱歉，当时移除 opencv 的目的主要是为了 lib 库更小，所以 opencv 的集成只能靠你自己啦 :)

**Comment by actionLUO** [comment]
@rochou 您好，你继承了opencv了吗？

**Comment by rochou** [comment]
@actionLUO 抱歉，我也没有整合，有兴趣可以一起试试看

**Comment by actionLUO** [comment]
@rochou 好啊，我很菜，分割网络您做过吗？

**Comment by rochou** [comment]
@actionLUO 我也很菜，分割网络还没接触过，偏应用，在想办法在移动端实现lcnn

**Comment by actionLUO** [comment]
@rochou 方便留个联系方式吗？交流一下经验

**Comment by rochou** [comment]
fs4now@yahoo.com，在你github主页没看到邮箱，这个是我的
