### ISSUE TITLE
Mac系统下编译.build_android.sh问题

### ISSUE THREAD

**Issue by actionLUO** [solrex/caffe-mobile#48]
![tmp](https://user-images.githubusercontent.com/21237742/39612512-b95220c6-4f92-11e8-9640-60e1ebae857f.jpg)

**Comment by solrex** [comment]
@actionLUO 不知道你 NDK 用的哪个版本？我记得某个版本（好像是16）之后头还是库文件的位置发生了改变。

**Comment by actionLUO** [comment]
您好，我又来打扰您了，我一直报错显示Could NOT find GFlags (missing: GFLAGS_INCLUDE_DIR GFLAGS_LIBRARY)，我用brew install glags安装了，但是还是报错！
