### ISSUE TITLE
能提供下net.protobin的原文件net.prototxt

### ISSUE THREAD

**Issue by guoqiang01486** [solrex/caffe-mobile#50]
首先 非常感谢您共享如此杰出的代码.
如果可以的话 可否提供下net.protobin的原文件net.prototxt 作为参考修改的模版 因为我不太了解文件的输入数据层和网络输出层的配置写法
非常感谢!

**Comment by solrex** [comment]
@guoqiang01486 net.prototxt 就是 Caffe 源码里面的 caffe/examples/mnist/lenet.prototxt 稍微做一些更改，README.md 中 Step2 有写。
