### ISSUE TITLE
./tools/build_android.sh

### ISSUE THREAD

**Issue by peterpaniff** [solrex/caffe-mobile#58]
CMakeFiles/caffe-jni.dir/caffe_mobile.cpp.o:caffe_mobile.cpp:function caffe::LogMessage::print(): error: undefined reference to '__android_log_print'

**Comment by peterpaniff** [comment]
请问下我编译的时候这个大概是什么原因呢？有没有解决的方法

**Comment by solrex** [comment]
@peterpaniff 你有没有修改编译脚本？这个的意思是没找到android log库的引用，也就是 -llog 没有找到链接库。

**Comment by peterpaniff** [comment]
> @peterpaniff 你有没有修改编译脚本？这个的意思是没找到android log库的引用，也就是 -llog 没有找到链接库。

谢谢，我已经解决问题了，我是修改了脚本
