### ISSUE TITLE
can not resolve protobin？

### ISSUE THREAD

**Issue by peterpaniff** [solrex/caffe-mobile#60]
I train a caffemodel on PC, i use the custom layer. _I test it on PC,  It show the correct result. But when i move it to  the android, it shows "ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: /storage/emulated/0/Demo/model/test.protobin". Could you please give me some hint to solve it. Thank you very much.

**Comment by solrex** [comment]
@peterpaniff You should add custom layers to caffe-mobile src/caffe/proto/caffe.proto. Then rebuild caffe-mobile to generate new pb.h/pb.cc and link into the new .so.

**Comment by peterpaniff** [comment]
I solved it, the protobin generated by windows environment is different from those by linux. When I change the environment to linux, It works。
