### ISSUE TITLE
caffe simple has been stoped

### ISSUE THREAD

**Issue by ferdinan97** [solrex/caffe-mobile#64]
i try to run the program in root/example/android/caffesimple the build process complete but when the application force close over and over again. how can i solve this ?

**Comment by solrex** [comment]
Can you provide more information? For example, android logcat error/warning logs.

**Comment by ferdinan97** [comment]
i already solve this problem it's just i didn't push the net.protobin to sd card

**Comment by ferdinan97** [comment]
but sir @solrex can you tell me how to train my own dataset for faster-r-cnn using vgg16?
