### ISSUE TITLE
Apple Mach-O Linker(Id) Error

### ISSUE THREAD

**Issue by xqpinitial** [solrex/caffe-mobile#7]
apple Mach-O Linker(Id) Error
caffe::Timer::~Timer() referenced from
caffe::CPUTimer::Start() reference from
caffe::Net<float>::Net(std::_1::basic_string<char,std::_1::char_traits<char>>...)

the libcaffe.a and libproto.a have been getted in build/lib

**Comment by solrex** [comment]
Sorry. I cannot understand your problem. Could you please clean your env, try again and provide more information?

**Comment by xqpinitial** [comment]
I'm soory i did't make it clear.
when i build caffe-mobile lib with cmake for Iphone,there is no problem for cmake and make -j4
however,when i start with xcode to build it by Command-R ,there is a error,Apple Mach-O Linker(Id) Error
![03c5a8f3-a061-49c0-9d73-f2c35b29e64a](https://cloud.githubusercontent.com/assets/16042607/25035931/4a53f5da-2123-11e7-90a0-19902277a1e6.png)

**Comment by solrex** [comment]
@xqpinitial It seems like you build caffe-mobile for iPhone, but build CaffeSimple for iPhoneSimulator. Connect your iPhone to Xcode, select one of your "Devices" instead of "iOS Simulators", then Cmd+R. Have fun! ^_^

![image](https://cloud.githubusercontent.com/assets/1180139/25038369/2272c510-2131-11e7-9273-d3357b29e68b.png)

**Comment by xqpinitial** [comment]
thanks for your answer,but ...i want to cry 
![2017-04-14 4 59 07](https://cloud.githubusercontent.com/assets/16042607/25038931/c179ccba-2133-11e7-86a3-360db8187de2.png)

**Comment by solrex** [comment]
@xqpinitial Right click on the first error, select "Reveal in log" menu. The whole log will be showed in the log message window. Normally this error is introduced by link to a libcaffe.a which is built for another architecture. 

For example:

WRONG CASE1: You built CaffeSimple for iPhone, linked to a libcaffe.a(libprotobuf.a) for iPhoneSimulator:

![image](https://cloud.githubusercontent.com/assets/1180139/25039623/1cb47ece-2137-11e7-9432-5740f01ec5c7.png)

WRONG CASE2: You built CaffeSimple for iPhoneSimulator, linked to a libcaffe.a(libprotobuf.a) for iPhone:

![image](https://cloud.githubusercontent.com/assets/1180139/25039756/f9267894-2137-11e7-9a09-1bd20b9d3a5b.png)

So please follow the instructions for different target in README.md **STEP by STEP**, if you don't know how to cleaning up your environment for different targets. It's really important.

**Comment by xqpinitial** [comment]
Thank you for your patience，I have runing your demo on my mobile with noproblem. I'm sorry i have trouble you. I have never using mac and iphone ,three days ago i try to translate caffe to iphone,i study how to use mac and xcode for one day, and then learn your demo。Because I do not understand the foundation, and bring you the trouble, please also please  understand

**Comment by solrex** [comment]
@xqpinitial Never mind ^_^
