### ISSUE TITLE
protocbuf.a is to large

### ISSUE THREAD

**Issue by xqpinitial** [solrex/caffe-mobile#8]
非常感谢您提供demo，前几天在您的提示simulation和真机的区别下我做好的demo，本来以为ok啦，却发现由于protobuf生成的.a太大，想在工程的基础上，分理处初始化函数，分类函数，全局变量_net，生成动态链接库，不知道是否可以，谢谢

**Comment by solrex** [comment]
@xqpinitial It won't affect the final app size.

**Comment by xqpinitial** [comment]
我生成的app中，把所有用到的.a都打包进去啦，到了170+M。。。

**Comment by xqpinitial** [comment]
如果可以我是否可以给您发邮件，谢谢

**Comment by xqpinitial** [comment]
![screenshot from 2017-04-19 17 02 43](https://cloud.githubusercontent.com/assets/16042607/25171976/3376e0a4-2522-11e7-976b-1f1b8986d600.png)
iPhone版本下，生成的protobuf太大

**Comment by solrex** [comment]
@xqpinitial I don't think copying `*.a`s to ipa is needed. But I'm not professional on that. You should consult some experts on that topic.

**Comment by xqpinitial** [comment]
thanks for you answer,i will try it
