### ISSUE TITLE
How to build .so file for android which ABIS is armeabi?

### ISSUE THREAD

**Issue by husteleven** [solrex/caffe-mobile#9]
Hello
      The ABIS of my phone is armeabi whice doesn‘t match your ABIS in .so file, and so can not run your demo. Could you have any idea to build the .so file for android which ABIS is armeabi?

**Comment by solrex** [comment]
@husteleven This commit solved your question: https://github.com/solrex/caffe-mobile/commit/a55c746909b76d8b898545b9e7aa68f820cbbd00

armeabi is slower than arm64-v8a, but working. However, armeabi-v7a (with NEON) still has some problem with OpenBLAS.
